use casper_types::ApiError;

#[repr(u16)]
#[derive(Clone, Copy)]
pub enum Error {
    InvalidAccount = 1,
    MissingInstaller = 2,
    InvalidContext = 3,
    InvalidIdentifierMode = 4,
    MissingTokenID = 5,
    InvalidTokenIdentifier = 6,
    FailedToGetArgBytes = 7,
    InvalidContractOwner = 8,
    RequestIdIlledFormat = 9,
    FailedToCreateDictionary = 10,
    RequestIdRepeated = 11,
    MissingKey = 12,
    SerilizationError = 13,
    UnlockIdRepeated = 14,
    FailedToCreateDictionaryUnlockIds = 15,
    ContractAlreadyInitialized = 16,
    CallerMustBeAccountHash = 17,
    TooManyTokenIds = 18,
    UnlockIdIllFormatted = 19,
    TxHashUnlockIdIllFormatted = 20,
    InvalidDev = 100,
    InvalidWrappedToken = 101,
    OnlyOwnerCanRevoke = 102,
    UnsupportedToken = 103,
    AskForMore = 104,    
    OnlyBidderCanRevoke = 105,
    MissingFeePortion = 106,
    InvalidFeePortion = 107,
    NftIsNotApproved = 108,
    BidTooLow = 109,
    BidInactive = 110,
    OnlyOfferorCanRevoke = 111,
    OfferInactive = 112,
    OnlyBidderCanIncreaseBid = 113,
    FeeTooHigh = 114,
    OnlyOwnerCanOffer = 115,
    MissingContractOwner = 116,
    ContractIllFormatted = 117,
    MissingWcsprContract = 118,
    InvalidWcsprContract = 119,
    MissingFeeReceiver = 120,
    InvalidFeeReceiver = 121,
    MissingOfferer = 122,
    AlreadyMakeOffer = 123,
    MissingRoyaltyFee = 124,
    InvalidRoyaltyFee = 125,
    MissingIsRoyalty = 126,
    InvalidIsRoyalty = 127,
    SameIsRoyalty = 128,
    MissingTokenMarketList = 129,
    InvalidTokenMarketList = 130,
    MissingAmount = 131,
    InvalidAmount = 132,
    CannotGetAmount = 133,
    NotEnoughAmount = 134,
    MissingSrcPurse = 135,
    InvalidSrcPurse = 136,
    CanNotGetUserPurse = 137,
    CanNotTransferCSPR = 138,
    MissingNFTContract = 139,
    InvalidNFTContract = 140,
    CanNotGetNFTContract = 141,
    CanNotGetTokenId = 142,
    MissingBuyer = 143,
    InvalidBuyer = 144,
    CanNotGetBuyer = 145,
    MissingContractPurse = 146,
    InvalidContractPurse = 147,
    InvalidInputTokenInfo = 148,
    WaitBeforeRamp = 149,
    InsufficientRampTime = 150,
    FutureAMustBeGood = 151,
    FutureATooSmall = 152,
    FutureATooLarge = 153,
    RampAlreadyStopped = 154,
    TokenNotFound = 155,
    ApproximationNotConverge = 156,
    DNotConverge = 157,
    BalancesMustMatchMultipliers = 158,
    WithdrawExceedAvailable = 159,
    TokenIndexOutOfRange = 160,
    WithdrawTooMuch = 161,
    ExceedSupply = 162,
    CantCompareTokenToItself = 163,
    TokenMustInPool = 164,
    CannotSwapMoreThanYouHave = 165,
    SwapNotResultInMinToken = 166,
    AmountsNotMatchPooledTokens = 167,
    MustSupplyAllTokensInPool = 168,
    DShouldIncrease = 169,
    CouldNotMintMinRequested = 170,
    GreaterLPBalanceOf = 171,
    MinAmounsMustMatchPooledTokens = 172,
    MinAmountsTooHigh = 173,
    DYLessThanAmount = 174,
    BurnAmountCannotZero = 175,
    TokenAmountGreaterThanMaxBurn = 176,
    PooledTokensLength = 177,
    PooledTokensDecimalsMismatch = 178,
    DuplicateToken = 179,
    TokenDecimalsExceedMax = 180,
    InvalidInitializedParams = 181,
    DeadlineNotMet = 182,
    ContractPaused = 183,
    ContractLocked = 184
}

impl From<Error> for ApiError {
    fn from(e: Error) -> Self {
        ApiError::User(e as u16)
    }
}
